<a href="https://colab.research.google.com/github/songqsh/ma2071_v01/blob/master/src/19final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 19 Final
[pdf](../doc/19final_a_v01.pdf)

In [ ]:
import numpy as np
import numpy.linalg as la

- Matrix $A = [a_1, a_2, a_3]$

In [ ]:
A = np.array([[0, -1, 0], [-1, 0, 0], [-1,-1,1]])
a1 = A[:,0]
a2 = A[:,1]
a3 = A[:,2]
print(A)

[[ 0 -1  0]
 [-1  0  0]
 [-1 -1  1]]


- Find $A^2$

In [ ]:
ans = np.matmul(A,A)
print(ans)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


- Is $a_2 \perp a_3$?

In [ ]:
ans = np.dot(a2, a3)
print(ans)
if ans == 0:
    print('yes')
else:
    print('no')

-1
no


- Find inverse of $A$

In [ ]:
ans = la.inv(A)
print(ans)

[[-0. -1. -0.]
 [-1. -0. -0.]
 [-1. -1.  1.]]


- deteminant of $A$

In [ ]:
ans1 = la.det(A)
ans2 = la.matrix_rank(A)
print(f'determinant is {ans1}, \n and rank is {ans2}')

determinant is -1.0, 
 and rank is 3


- compute eigenvalue and eigenspace

In [ ]:
ans1, ans2 = la.eig(A)
print(f'eigenvalues are {ans1} \n and eigenspaces are \n {ans2}')

eigenvalues are [ 1.  1. -1.] 
 and eigenspaces are 
 [[ 0.         -0.70710678  0.57735027]
 [ 0.          0.70710678  0.57735027]
 [ 1.          0.          0.57735027]]


- diagonalize $A$, i.e. $A = PDP^{-1}$.

In [ ]:
D = np.diag(ans1)
P = ans2
#P@D@la.inv(P) #check
print(f' D is \n {D}, \n P is \n {P}')

 D is 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]], 
 P is 
 [[ 0.         -0.70710678  0.57735027]
 [ 0.          0.70710678  0.57735027]
 [ 1.          0.          0.57735027]]


- Project $a_2$ on $a_3$

In [ ]:
a3n = a3/la.norm(a3)
ans = np.dot(A[:,1], a3n)*a3n
print(ans)

[-0. -0. -1.]


- project $a_1$ to $span(a_2, a_3)$

In [ ]:
a2p = a2 - ans
a2n = a2p/la.norm(a2p)
prj = np.dot(a1, a2n)*a2n+np.dot(a1,a3n)*a3n
print(prj)

[-0.  0. -1.]


In [ ]:
#alternative method
B = A[:, 1:]
prj1 = B@la.inv(np.transpose(B)@B)@np.transpose(B)@a1
print(prj1)

[ 0.  0. -1.]


- find $A^{2019}$

In [ ]:
print(la.matrix_power(A,2019))

[[ 0 -1  0]
 [-1  0  0]
 [-1 -1  1]]
