In [1]:
import numpy as np
import numpy.linalg as la

- Matrix $A = [a_1, a_2, a_3]$

In [2]:
A = np.array([[0, -1, 0], [-1, 0, 0], [-1,-1,1]])
print(A)

[[ 0 -1  0]
 [-1  0  0]
 [-1 -1  1]]


- Find $A^2$

In [3]:
ans = np.matmul(A,A)
print(ans)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


- Is $a_2 \perp a_3$?

In [4]:
ans = np.dot(A[:, 1], A[:,2])
if ans == 0:
    print('yes')
else:
    print('no')

no


- Find inverse of $A$

In [5]:
ans = la.inv(A)
print(ans)

[[-0. -1. -0.]
 [-1. -0. -0.]
 [-1. -1.  1.]]


- deteminant of $A$

In [6]:
ans1 = la.det(A)
ans2 = la.matrix_rank(A)
print(f'determinant is {ans1}, \n and rank is {ans2}')

determinant is -1.0, 
 and rank is 3


- compute eigenvalue and eigenspace

In [7]:
ans1, ans2 = la.eig(A)
print(f'eigenvalues are {ans1} \n and eigenspaces are \n {ans2}')

eigenvalues are [ 1.  1. -1.] 
 and eigenspaces are 
 [[ 0.         -0.70710678  0.57735027]
 [ 0.          0.70710678  0.57735027]
 [ 1.          0.          0.57735027]]


- diagonalize $A$, i.e. $A = PDP^{-1}$.

In [8]:
D = np.diag(ans1)
P = ans2
#P@D@la.inv(P) #check
print(f' D is \n {D}, \n P is \n {P}')

 D is 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]], 
 P is 
 [[ 0.         -0.70710678  0.57735027]
 [ 0.          0.70710678  0.57735027]
 [ 1.          0.          0.57735027]]


- Project $a_2$ on $a_3$

In [9]:
a3n = A[:,2]/la.norm(A[:,2])
ans = np.dot(A[:,1], a3n)*a3n
print(ans)

[-0. -0. -1.]


- project $a_1$ to $span(a_2, a_3)$

In [19]:
a2 = A[:,1]- ans
a2n = a2/la.norm(a2)
a1 = A[:,0]
prj = np.dot(a1, a2n)*a2n+np.dot(a1,a3n)*a3n
print(prj)

[-0.  0. -1.]


- find $A^{2019}$

In [20]:
print(la.matrix_power(A,2019))

[[ 0 -1  0]
 [-1  0  0]
 [-1 -1  1]]
