<a href="https://colab.research.google.com/github/songqsh/ma2071_v01/blob/master/src/20writtenhw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Written Homework 3

In [0]:
import numpy as np
import numpy.linalg as la

In [0]:
# eigenvalues
lam1 = 2; lam2 = -2; lam3 = 4

In [0]:
#eigenvectors
v1 = np.array([1,-1, 0])
v2 = np.array([0, 1, 1])
v3 = np.array([-1,0, 1])

In [178]:
# constructing matrix $A$
D = np.diag([lam1,lam2,lam3])
print('D is:\n', D)
V = np.transpose(np.array([v1, v2, v3]))
print('V is:\n', V)
A = V@D@la.inv(V)
print('A is:\n', A)

D is:
 [[ 2  0  0]
 [ 0 -2  0]
 [ 0  0  4]]
V is:
 [[ 1  0 -1]
 [-1  1  0]
 [ 0  1  1]]
A is:
 [[ 3.  1. -1.]
 [-2.  0. -2.]
 [-3. -3.  1.]]


- Find determinant of $A$

In [179]:
la.det(A)
# should integer

-15.999999999999998

- Is $A$ invertible? If yes, find its inverse

In [180]:
la.inv(A)

array([[ 0.375, -0.125,  0.125],
       [-0.5  , -0.   , -0.5  ],
       [-0.375, -0.375, -0.125]])

- Find all eigenvalues

In [181]:
np.diag(D)

array([ 2, -2,  4])

- Find all corresponding eigenvectors with $3$ being the first entry

In [182]:
print(3*v1)
print(3*v2)
print(-3*v3)

[ 3 -3  0]
[0 3 3]
[ 3  0 -3]


- Find $A^{5}$

In [191]:
# one way
n = 5
la.matrix_power(A,n)

array([[ 528.,  496., -496.],
       [ -32.,    0.,  -32.],
       [-528., -528.,  496.]])

In [190]:
# second way
n = 5
V@np.diag([2**n, (-2)**n, 4**n])@la.inv(V)

array([[ 528.,  496., -496.],
       [ -32.,    0.,  -32.],
       [-528., -528.,  496.]])