# Gaussian elimination: Convert a matrix to an Reduced Row Echelon Form (RREF)

In [1]:
# import package
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)

## Matrix in numpy

In [2]:
# input matrix
A = np.array([[.2, .17, .25, .2, .1],
              [.25, .2, .1, .3, 0],
              [.05, .2, .1, .15, .1]])
A # print A

array([[0.2 , 0.17, 0.25, 0.2 , 0.1 ],
       [0.25, 0.2 , 0.1 , 0.3 , 0.  ],
       [0.05, 0.2 , 0.1 , 0.15, 0.1 ]])

In [3]:
# indexing is starting from 0, not from 1
# ex. print the third row
A[2]

array([0.05, 0.2 , 0.1 , 0.15, 0.1 ])

In [4]:
# ex. print the entry at 2nd row 4th column
A[1,3]

0.3

## How to RREF

In [5]:
# We will reduce the matrix A into RREF
A

array([[0.2 , 0.17, 0.25, 0.2 , 0.1 ],
       [0.25, 0.2 , 0.1 , 0.3 , 0.  ],
       [0.05, 0.2 , 0.1 , 0.15, 0.1 ]])

### Forward elimination

In [6]:
# R1/0.2 --> R1
A[0] = A[0] / 0.2
A #print

array([[1.  , 0.85, 1.25, 1.  , 0.5 ],
       [0.25, 0.2 , 0.1 , 0.3 , 0.  ],
       [0.05, 0.2 , 0.1 , 0.15, 0.1 ]])

In [7]:
# R2 - R1*.25 --> R2
# R3 - R1*.05 -->R3
A[1] = A[1] - A[0]*.25
A[2] = A[2] - A[0]*.05
A

array([[ 1.    ,  0.85  ,  1.25  ,  1.    ,  0.5   ],
       [ 0.    , -0.0125, -0.2125,  0.05  , -0.125 ],
       [ 0.    ,  0.1575,  0.0375,  0.1   ,  0.075 ]])

In [8]:
# R2/ (-.0125) -->R2
A[1] = A[1]*(-80)
A

array([[ 1.    ,  0.85  ,  1.25  ,  1.    ,  0.5   ],
       [-0.    ,  1.    , 17.    , -4.    , 10.    ],
       [ 0.    ,  0.1575,  0.0375,  0.1   ,  0.075 ]])

In [9]:
# R3 - R2*.1575 -->R3
A[2] = A[2] - A[1]*0.1575
A

array([[ 1.  ,  0.85,  1.25,  1.  ,  0.5 ],
       [-0.  ,  1.  , 17.  , -4.  , 10.  ],
       [ 0.  ,  0.  , -2.64,  0.73, -1.5 ]])

### Backward elimination

In [10]:
# R3/(-2.64) -->R3
A[2] = A[2]/(-2.64)
A

array([[ 1.        ,  0.85      ,  1.25      ,  1.        ,  0.5       ],
       [-0.        ,  1.        , 17.        , -4.        , 10.        ],
       [-0.        , -0.        ,  1.        , -0.27651515,  0.56818182]])

In [11]:
# R2 - R3*17 -->R2
# R1 - R3*1.25 -->R1
A[1] = A[1] - A[2]*17
A[0] = A[0] - A[2]*1.25
A

array([[ 1.        ,  0.85      ,  0.        ,  1.34564394, -0.21022727],
       [ 0.        ,  1.        ,  0.        ,  0.70075758,  0.34090909],
       [-0.        , -0.        ,  1.        , -0.27651515,  0.56818182]])

In [12]:
# R1 - R2*.85 -->R1
A[0] = A[0] - A[1]*.85
A

array([[ 1.        ,  0.        ,  0.        ,  0.75      , -0.5       ],
       [ 0.        ,  1.        ,  0.        ,  0.70075758,  0.34090909],
       [-0.        , -0.        ,  1.        , -0.27651515,  0.56818182]])