<a href="https://colab.research.google.com/github/songqsh/ma2071_v01/blob/master/src/linalg_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Confirm TensorFlow can see the GPU

- Simply select "GPU" in the Accelerator drop-down in Notebook Settings (either through the Edit menu or the command palette at cmd/ctrl-shift-P).

In [1]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [0]:
#import packages

import tensorflow as tf
import tensorflow.linalg as tfla
import numpy as np
import numpy.linalg as npla

In [0]:
#run a session
sess = tf.Session()

In [4]:
#matrix input
# 2-D tensor `a`

a = tf.constant([[1., -1, 0],        
                 [0, 2, 0],
                 [0., 1, 1]])


sess.run(a)


array([[ 1., -1.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  1.,  1.]], dtype=float32)

In [5]:
# identity matrix

id3 = tf.eye(3)
sess.run(id3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [6]:
#transpose

a_trans = tfla.transpose(a)
sess.run(a_trans)

array([[ 1.,  0.,  0.],
       [-1.,  2.,  1.],
       [ 0.,  0.,  1.]], dtype=float32)

In [7]:
#multiplication

prod = a @ a_trans

sess.run(prod)

array([[ 2., -2., -1.],
       [-2.,  4.,  2.],
       [-1.,  2.,  2.]], dtype=float32)

In [8]:
# solver of linear system

soln = tfla.solve(a, id3)
sess.run(soln)

array([[ 1. ,  0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]], dtype=float32)

In [9]:
#determinant

sess.run(tfla.det(a))

2.0

In [10]:
#inverse

a_inv = tfla.inv(a)
sess.run(a_inv)

array([[ 1. ,  0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]], dtype=float32)

In [11]:
# check inverse

sess.run(a@a_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [12]:
#change tensor to numpy array

a_np = sess.run(a)

type(a_np)

numpy.ndarray

In [13]:
# eigen decomposition
# this is not available in tf, so we have to use np

a_eig_val, a_eig_vec = npla.eig(a_np)
print(a_eig_val)
print(a_eig_vec)

[1. 1. 2.]
[[ 1.          0.         -0.57735026]
 [ 0.          0.          0.57735026]
 [ 0.          1.          0.57735026]]
