In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
A = np.array([[15, 15], [10, 6]])
A

array([[15, 15],
       [10,  6]])

In [3]:
B = np.array([[8, 22], [1, 9]])
B

array([[ 8, 22],
       [ 1,  9]])

In [5]:
np.matmul(A, la.inv(B))

array([[ 2.4 , -4.2 ],
       [ 1.68, -3.44]])